/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercise_49;

import javax.swing.JOptionPane;

/**
 * Date: 12/12/2025
 * Function: Hangman_1
 * @author Vissolela Cundi
 */
public class Hangman1 extends javax.swing.JFrame {
    public int letter;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Hangman1.class.getName());

    /**
     * Creates new form Hangman1
     */
    public Hangman1() {
        initComponents();
        lblLetter1.setVisible(false);
        lblLetter2.setVisible(false);
        lblLetter3.setVisible(false);
        lblLetter4.setVisible(false);
        lblLetter5.setVisible(false);
        lblLetter6.setVisible(false);
        lblLetter7.setVisible(false);
        
        lblError_1.setVisible(false);
        lblError_2.setVisible(false);
        lblError_3.setVisible(false);
        lblError_4.setVisible(false);
    }
    
    public void verify_win() {
        if (letter == 7) {
            String msg = "<html>You Win! <br>Would you like to play again?";
            int value = JOptionPane.showConfirmDialog(null, msg);
        
            if (value == 0)
                start();
            else
                this.dispose();
        }
    }
    public void start() {
        lblError_0.setVisible(true);
        lblError_1.setVisible(false);
        lblError_2.setVisible(false);
        lblError_3.setVisible(false);
        lblError_4.setVisible(false);
        
        lblLetter1.setVisible(false);
        lblLetter2.setVisible(false);
        lblLetter3.setVisible(false);
        lblLetter4.setVisible(false);
        lblLetter5.setVisible(false);
        lblLetter6.setVisible(false);
        lblLetter7.setVisible(false);
        
        lblErrors.setText("0");
        
        btnA.setEnabled(true);
        btnB.setEnabled(true);
        btnC.setEnabled(true);
        btnD.setEnabled(true);
        btnE.setEnabled(true);
        btnF.setEnabled(true);
        btnG.setEnabled(true);
        btnH.setEnabled(true);
        btnI.setEnabled(true);
        btnJ.setEnabled(true);
        btnK.setEnabled(true);
        btnL.setEnabled(true);
        btnM.setEnabled(true);
        btnN.setEnabled(true);
        btnO.setEnabled(true);
        btnP.setEnabled(true);
        btnQ.setEnabled(true);
        btnR.setEnabled(true);
        btnS.setEnabled(true);
        btnT.setEnabled(true);
        btnU.setEnabled(true);
        btnV.setEnabled(true);
        btnW.setEnabled(true);
        btnX.setEnabled(true);
        btnY.setEnabled(true);
        btnZ.setEnabled(true);  
    }
    public void lost() {
        String msg = "<html>You Lose! <br>Would you like to play again?";
        int value = JOptionPane.showConfirmDialog(null, msg);
        
        if (value == 0)
            start();
        else
            this.dispose();
    }
    public void change_image() {
        int errors = Integer.parseInt(lblErrors.getText());
        errors++;
        lblErrors.setText(errors+"");
        
        if (errors == 1)
        {
            lblError_0.setVisible(false);
            lblError_1.setVisible(true);
        }
        else
            if (errors == 2)
            {
                lblError_1.setVisible(false);
                lblError_2.setVisible(true);
            }
            else
                if (errors == 3)
                {
                   lblError_2.setVisible(false);
                   lblError_3.setVisible(true);
                }
                else
                 {
                    lblError_3.setVisible(false);
                    lblError_4.setVisible(true);
                 }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnD = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        lblLetter4 = new javax.swing.JLabel();
        lblLetter3 = new javax.swing.JLabel();
        lblLetter2 = new javax.swing.JLabel();
        lblLetter1 = new javax.swing.JLabel();
        lblLines = new javax.swing.JLabel();
        lblErrors = new javax.swing.JLabel();
        lblLetter7 = new javax.swing.JLabel();
        lblLetter6 = new javax.swing.JLabel();
        lblLetter5 = new javax.swing.JLabel();
        lblError_0 = new javax.swing.JLabel();
        lblError_1 = new javax.swing.JLabel();
        lblError_2 = new javax.swing.JLabel();
        lblError_3 = new javax.swing.JLabel();
        lblError_4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman1");
        setMaximumSize(new java.awt.Dimension(650, 400));
        setMinimumSize(new java.awt.Dimension(650, 400));
        setPreferredSize(new java.awt.Dimension(650, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnD.setText("D");
        btnD.addActionListener(this::btnDActionPerformed);
        getContentPane().add(btnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 50, -1));

        btnC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(this::btnCActionPerformed);
        getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 50, -1));

        btnB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnB.setText("B");
        btnB.addActionListener(this::btnBActionPerformed);
        getContentPane().add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 50, -1));

        btnA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnA.setText("A");
        btnA.addActionListener(this::btnAActionPerformed);
        getContentPane().add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 50, -1));

        btnH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnH.setText("H");
        btnH.addActionListener(this::btnHActionPerformed);
        getContentPane().add(btnH, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 50, -1));

        btnG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnG.setText("G");
        btnG.addActionListener(this::btnGActionPerformed);
        getContentPane().add(btnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 50, -1));

        btnF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnF.setText("F");
        btnF.addActionListener(this::btnFActionPerformed);
        getContentPane().add(btnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 50, -1));

        btnE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnE.setText("E");
        btnE.addActionListener(this::btnEActionPerformed);
        getContentPane().add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 50, -1));

        btnL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnL.setText("L");
        btnL.addActionListener(this::btnLActionPerformed);
        getContentPane().add(btnL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 50, -1));

        btnK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnK.setText("K");
        btnK.addActionListener(this::btnKActionPerformed);
        getContentPane().add(btnK, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 50, -1));

        btnJ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnJ.setText("J");
        btnJ.addActionListener(this::btnJActionPerformed);
        getContentPane().add(btnJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 50, -1));

        btnI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnI.setText("I");
        btnI.addActionListener(this::btnIActionPerformed);
        getContentPane().add(btnI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 50, -1));

        btnP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnP.setText("P");
        btnP.addActionListener(this::btnPActionPerformed);
        getContentPane().add(btnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 50, -1));

        btnO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnO.setText("O");
        btnO.addActionListener(this::btnOActionPerformed);
        getContentPane().add(btnO, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 50, -1));

        btnN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnN.setText("N");
        btnN.addActionListener(this::btnNActionPerformed);
        getContentPane().add(btnN, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 50, -1));

        btnM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnM.setText("M");
        btnM.addActionListener(this::btnMActionPerformed);
        getContentPane().add(btnM, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 50, -1));

        btnT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnT.setText("T");
        btnT.addActionListener(this::btnTActionPerformed);
        getContentPane().add(btnT, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 50, -1));

        btnS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnS.setText("S");
        btnS.addActionListener(this::btnSActionPerformed);
        getContentPane().add(btnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 50, -1));

        btnR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnR.setText("R");
        btnR.addActionListener(this::btnRActionPerformed);
        getContentPane().add(btnR, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 50, -1));

        btnQ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQ.setText("Q");
        btnQ.addActionListener(this::btnQActionPerformed);
        getContentPane().add(btnQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 50, -1));

        btnX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnX.setText("X");
        btnX.addActionListener(this::btnXActionPerformed);
        getContentPane().add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 50, -1));

        btnW.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnW.setText("W");
        btnW.addActionListener(this::btnWActionPerformed);
        getContentPane().add(btnW, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 50, -1));

        btnV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnV.setText("V");
        btnV.addActionListener(this::btnVActionPerformed);
        getContentPane().add(btnV, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 50, -1));

        btnU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnU.setText("U");
        btnU.addActionListener(this::btnUActionPerformed);
        getContentPane().add(btnU, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 50, -1));

        btnY.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnY.setText("Y");
        btnY.addActionListener(this::btnYActionPerformed);
        getContentPane().add(btnY, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 50, -1));

        btnZ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnZ.setText("Z");
        btnZ.addActionListener(this::btnZActionPerformed);
        getContentPane().add(btnZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 50, -1));

        lblLetter4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLetter4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLetter4.setText("L");
        getContentPane().add(lblLetter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 40, 70));

        lblLetter3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLetter3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLetter3.setText("O");
        getContentPane().add(lblLetter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, 70));

        lblLetter2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLetter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLetter2.setText("O");
        getContentPane().add(lblLetter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 40, 70));

        lblLetter1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLetter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLetter1.setText("B");
        getContentPane().add(lblLetter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 40, 70));

        lblLines.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLines.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLines.setText("_  _  _  _  _  _  _");
        lblLines.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblLines, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 310, 20));

        lblErrors.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblErrors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrors.setText("0");
        getContentPane().add(lblErrors, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 30, 50));

        lblLetter7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLetter7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLetter7.setText("N");
        getContentPane().add(lblLetter7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 40, 70));

        lblLetter6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLetter6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLetter6.setText("A");
        getContentPane().add(lblLetter6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, 70));

        lblLetter5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLetter5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLetter5.setText("E");
        getContentPane().add(lblLetter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 40, 70));

        lblError_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercise_49/erro_0.jpg"))); // NOI18N
        getContentPane().add(lblError_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 160));

        lblError_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercise_49/erro_1.jpg"))); // NOI18N
        getContentPane().add(lblError_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 160));

        lblError_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercise_49/erro_2.jpg"))); // NOI18N
        getContentPane().add(lblError_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 160));

        lblError_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercise_49/erro_3.jpg"))); // NOI18N
        getContentPane().add(lblError_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 160));

        lblError_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercise_49/erro_4.jpg"))); // NOI18N
        getContentPane().add(lblError_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        // TODO add your handling code here:
        this.btnD.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnDActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        this.btnC.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();

    }//GEN-LAST:event_btnCActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // TODO add your handling code here:
        letter++;
        lblLetter1.setVisible(true);
        this.btnB.setEnabled(false);
        verify_win();
    }//GEN-LAST:event_btnBActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
        letter++;
        lblLetter6.setVisible(true);
        this.btnA.setEnabled(false);
        verify_win();
    }//GEN-LAST:event_btnAActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
        // TODO add your handling code here:
        this.btnH.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnHActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        // TODO add your handling code here:
        this.btnG.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnGActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        // TODO add your handling code here:
        this.btnF.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnFActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:
        letter++;
        lblLetter5.setVisible(true);
        this.btnE.setEnabled(false);
        verify_win();
    }//GEN-LAST:event_btnEActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        // TODO add your handling code here:
        letter++;
        lblLetter4.setVisible(true);
        this.btnL.setEnabled(false);
        verify_win();
    }//GEN-LAST:event_btnLActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
        // TODO add your handling code here:
        this.btnK.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnKActionPerformed

    private void btnJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJActionPerformed
        // TODO add your handling code here:
        this.btnZ.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnJActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
        // TODO add your handling code here:
        this.btnI.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnIActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        // TODO add your handling code here:
        this.btnP.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnPActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        // TODO add your handling code here:
        letter++;
        lblLetter2.setVisible(true);
        letter++;
        lblLetter3.setVisible(true);
        this.btnO.setEnabled(false);
        verify_win();
    }//GEN-LAST:event_btnOActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        // TODO add your handling code here:
        letter++;
        lblLetter7.setVisible(true);
        this.btnN.setEnabled(false);
        verify_win();
    }//GEN-LAST:event_btnNActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        // TODO add your handling code here:
        this.btnM.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnMActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        // TODO add your handling code here:
        this.btnT.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnTActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        // TODO add your handling code here:
        this.btnS.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnSActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        // TODO add your handling code here:
        this.btnR.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnRActionPerformed

    private void btnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQActionPerformed
        // TODO add your handling code here:
        this.btnQ.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnQActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        // TODO add your handling code here:
        this.btnX.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnXActionPerformed

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
        // TODO add your handling code here:
        this.btnW.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnWActionPerformed

    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
        // TODO add your handling code here:
        this.btnZ.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnVActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        // TODO add your handling code here:
        this.btnU.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnUActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
        // TODO add your handling code here:
        this.btnY.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnYActionPerformed

    private void btnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZActionPerformed
        // TODO add your handling code here:
        this.btnZ.setEnabled(false);
        int errors = Integer.parseInt(lblErrors.getText());

        if (errors == 4)
        lost();
        else
        change_image();
    }//GEN-LAST:event_btnZActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Hangman1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnA;
    public javax.swing.JButton btnB;
    public javax.swing.JButton btnC;
    public javax.swing.JButton btnD;
    public javax.swing.JButton btnE;
    public javax.swing.JButton btnF;
    public javax.swing.JButton btnG;
    public javax.swing.JButton btnH;
    public javax.swing.JButton btnI;
    public javax.swing.JButton btnJ;
    public javax.swing.JButton btnK;
    public javax.swing.JButton btnL;
    public javax.swing.JButton btnM;
    public javax.swing.JButton btnN;
    public javax.swing.JButton btnO;
    public javax.swing.JButton btnP;
    public javax.swing.JButton btnQ;
    public javax.swing.JButton btnR;
    public javax.swing.JButton btnS;
    public javax.swing.JButton btnT;
    public javax.swing.JButton btnU;
    public javax.swing.JButton btnV;
    public javax.swing.JButton btnW;
    public javax.swing.JButton btnX;
    public javax.swing.JButton btnY;
    public javax.swing.JButton btnZ;
    public javax.swing.JLabel lblError_0;
    public javax.swing.JLabel lblError_1;
    public javax.swing.JLabel lblError_2;
    public javax.swing.JLabel lblError_3;
    public javax.swing.JLabel lblError_4;
    private javax.swing.JLabel lblErrors;
    public javax.swing.JLabel lblLetter1;
    public javax.swing.JLabel lblLetter2;
    public javax.swing.JLabel lblLetter3;
    public javax.swing.JLabel lblLetter4;
    public javax.swing.JLabel lblLetter5;
    public javax.swing.JLabel lblLetter6;
    public javax.swing.JLabel lblLetter7;
    private javax.swing.JLabel lblLines;
    // End of variables declaration//GEN-END:variables
}
