/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercise_51;

import javax.swing.JOptionPane;
import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
       


/**
 * Date: 05/01/2026
 * Function: Pokemon Game
 * @author Vissolela Cundi
 */
public class Pokemon extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pokemon.class.getName());

    /**
     * Creates new form Pokemon
     */
    public Pokemon() {
        initComponents();
    }
    
    public void right() {
    try{
        File wav = new File("c:\\temp1\\sucesso.wav");
        Clip clip = AudioSystem.getClip();
        clip.open(AudioSystem.getAudioInputStream(wav));
        
        clip.start();    
    }
        catch(Exception e){
        e.printStackTrace();
        }
    }
    
    public void won() {
    try{
        File wav = new File("c:\\temp1\\ganhou.wav");
        Clip clip = AudioSystem.getClip();
        clip.open(AudioSystem.getAudioInputStream(wav));
        
        clip.start();    
    }
        catch(Exception e){
        e.printStackTrace();
        }
    }
    
    public void wrong() {
    try{
        File wav = new File("c:\\temp1\\erro.wav");
        Clip clip = AudioSystem.getClip();
        clip.open(AudioSystem.getAudioInputStream(wav));
        
        clip.start();    
    }
        catch(Exception e){
        e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_value = new javax.swing.JLabel();
        lbl_points = new javax.swing.JLabel();
        lbl_pic1 = new javax.swing.JLabel();
        lbl_pic2 = new javax.swing.JLabel();
        lbl_pic3 = new javax.swing.JLabel();
        lbl_pic4 = new javax.swing.JLabel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        lbl_monster = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemon");
        setMaximumSize(new java.awt.Dimension(840, 360));
        setMinimumSize(new java.awt.Dimension(840, 360));
        setPreferredSize(new java.awt.Dimension(840, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_value.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_value.setText("0");
        getContentPane().add(lbl_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 90, 30));

        lbl_points.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_points.setText("Points");
        getContentPane().add(lbl_points, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 90, 30));

        lbl_pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercise_51/pic1.jpg"))); // NOI18N
        getContentPane().add(lbl_pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 170));

        lbl_pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercise_51/pic2.jpg"))); // NOI18N
        getContentPane().add(lbl_pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 170, 170));

        lbl_pic3.setIcon(new javax.swing.ImageIcon("C:\\Users\\cundi\\Downloads\\exercise51\\Projeto\\pic3.jpg")); // NOI18N
        getContentPane().add(lbl_pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 170, 170));

        lbl_pic4.setIcon(new javax.swing.ImageIcon("C:\\Users\\cundi\\Downloads\\exercise51\\Projeto\\pic4.jpg")); // NOI18N
        getContentPane().add(lbl_pic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 91, 170, -1));

        btn_1.setText("?");
        btn_1.addActionListener(this::btn_1ActionPerformed);
        getContentPane().add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, -1));

        btn_2.setText("?");
        btn_2.addActionListener(this::btn_2ActionPerformed);
        getContentPane().add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 170, -1));

        btn_3.setText("?");
        btn_3.addActionListener(this::btn_3ActionPerformed);
        getContentPane().add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 170, -1));

        btn_4.setText("?");
        btn_4.addActionListener(this::btn_4ActionPerformed);
        getContentPane().add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 170, -1));

        lbl_monster.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_monster.setForeground(new java.awt.Color(0, 51, 204));
        lbl_monster.setText("venusaur");
        getContentPane().add(lbl_monster, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 260, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        if (btn_1.getText() == "?")
        {
            if (lbl_monster.getText() == "bulbasaur")
            {
                double points = Double.parseDouble(lbl_value.getText());
                points = points + 10;
                lbl_value.setText(""+points);
                right();
                JOptionPane.showMessageDialog(null, "Caught one!");
                lbl_monster.setText("wartortle");
                btn_1.setText("bulbasaur");
            }
            else
            {
                double points = Double.parseDouble(lbl_value.getText());
                points = points - 10;
                lbl_value.setText(""+points);
                wrong();
                JOptionPane.showMessageDialog(null, "Try again!");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "This one has been caught already!");
        }
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        if (btn_2.getText() == "?")
        {
            if (lbl_monster.getText() == "wartortle")
            {
                double points = Double.parseDouble(lbl_value.getText());
                points = points + 10;
                lbl_value.setText(""+points);
                right();
                JOptionPane.showMessageDialog(null, "Caught one!");
                lbl_monster.setText("venusaur");
                btn_2.setText("wartortle");
                won();
            }
            else
            {
                double points = Double.parseDouble(lbl_value.getText());
                points = points - 10;
                lbl_value.setText(""+points);
                wrong();
                JOptionPane.showMessageDialog(null, "Try again!");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "This one has been caught already!");
        }
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        if (btn_3.getText() == "?")
        {
            if (lbl_monster.getText() == "venusaur")
            {
                double points = Double.parseDouble(lbl_value.getText());
                points = points + 10;
                lbl_value.setText(""+points);
                right();
                JOptionPane.showMessageDialog(null, "Caught one!");
                lbl_monster.setText("victreebel");
                btn_3.setText("venusaur");
            }
            else
            {
                double points = Double.parseDouble(lbl_value.getText());
                points = points - 10;
                lbl_value.setText(""+points);
                wrong();
                JOptionPane.showMessageDialog(null, "Try again!");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "This one has been caught already!");
        }
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        if (btn_4.getText() == "?")
        {
            if (lbl_monster.getText() == "victreebel")
            {
                double points = Double.parseDouble(lbl_value.getText());
                points = points + 10;
                lbl_value.setText(""+points);
                won();
                JOptionPane.showMessageDialog(null, "Caught all!");
                lbl_monster.setText("Congratulation!");
                btn_4.setText("victreebel");
            }
            else
            {
                double points = Double.parseDouble(lbl_value.getText());
                points = points - 10;
                lbl_value.setText(""+points);
                wrong();
                JOptionPane.showMessageDialog(null, "Try again!");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "This one has been caught already!");
        }
    }//GEN-LAST:event_btn_4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pokemon().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_1;
    public javax.swing.JButton btn_2;
    public javax.swing.JButton btn_3;
    public javax.swing.JButton btn_4;
    public javax.swing.JLabel lbl_monster;
    private javax.swing.JLabel lbl_pic1;
    private javax.swing.JLabel lbl_pic2;
    private javax.swing.JLabel lbl_pic3;
    private javax.swing.JLabel lbl_pic4;
    private javax.swing.JLabel lbl_points;
    public javax.swing.JLabel lbl_value;
    // End of variables declaration//GEN-END:variables
}
